#!/bin/sh

gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'
gsettings set org.gnome.desktop.interface gtk-theme 'Colloid-Grey-Dark'
gsettings set org.gnome.desktop.interface icon-theme 'Colloid-Grey-Dark'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
sed -i '3,8d' ~/.config/labwc/autostart

# Audio server
/etc/rc.d/service start audio

# Environment
dbus-update-activation-environment --all &

# Graphical shell
sysshell &

# Desktop icons
#frog -d &

# Background
swaybg -m fill -i /opt/setup/wallpapers/dark.jpg &

# Terminal
foot -s -S -d none &

# Auth
gnome-keyring-daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
