on: [push, pull_request]

jobs:
  aarch64_job:
    runs-on: ubuntu-24.04-arm
    name: Build on archarm_latest aarch64
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run commands
        run: uname -a
