on: [push, pull_request]

jobs:
  aarch64_job:
    runs-on: ubuntu-24.04-arm
    name: Create rootfs.img
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Make script executable
        run: chmod +x linux/distribution/install.sh
      - name: Run commands
        run: |
            cd distribution
            sudo ./install.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: distribution/rootfs.img
