on: 
  push:
    paths: ['distribution/**']

jobs:
  aarch64_job:
    runs-on: ubuntu-24.04-arm
    name: Create rootfs.img
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Restore cache
        id: cache-download
        uses: actions/cache@v4
        with:
          path: distribution/root.tar.xz
          key: downloaded-file-${{ runner.os }}-v1
          restore-keys: |
            downloaded-file-${{ runner.os }}-
      - name: Make script executable
        run: chmod +x ./distribution/install.sh
      - name: Run commands
        run: |
            cd ./distribution
            sudo ./install.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: rootfs
          path: ./distribution/rootfs.img
